"""expand etf_universe with tracking and active_set columns

Revision ID: 223e641c8d79
Revises: 4ac29fbec118
Create Date: 2026-03-15 14:03:15.635056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223e641c8d79'
down_revision: Union[str, None] = '4ac29fbec118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etf_universe', sa.Column('in_active_set', sa.Boolean(), nullable=True))
    op.add_column('etf_universe', sa.Column('active_set_reason', sa.String(length=200), nullable=True))
    op.add_column('etf_universe', sa.Column('active_set_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('etf_universe', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('etf_universe', sa.Column('your_rating', sa.Integer(), nullable=True))
    op.add_column('etf_universe', sa.Column('tags', sa.String(length=200), nullable=True))
    op.add_column('etf_universe', sa.Column('last_signal_type', sa.String(length=10), nullable=True))
    op.add_column('etf_universe', sa.Column('last_composite_score', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('etf_universe', sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('etf_universe', sa.Column('perf_1w', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('etf_universe', sa.Column('perf_1m', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('etf_universe', sa.Column('perf_3m', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('etf_universe', sa.Column('correlation_to_spy', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('etf_universe', sa.Column('added_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etf_universe', 'added_at')
    op.drop_column('etf_universe', 'correlation_to_spy')
    op.drop_column('etf_universe', 'perf_3m')
    op.drop_column('etf_universe', 'perf_1m')
    op.drop_column('etf_universe', 'perf_1w')
    op.drop_column('etf_universe', 'last_signal_at')
    op.drop_column('etf_universe', 'last_composite_score')
    op.drop_column('etf_universe', 'last_signal_type')
    op.drop_column('etf_universe', 'tags')
    op.drop_column('etf_universe', 'your_rating')
    op.drop_column('etf_universe', 'notes')
    op.drop_column('etf_universe', 'active_set_changed_at')
    op.drop_column('etf_universe', 'active_set_reason')
    op.drop_column('etf_universe', 'in_active_set')
    # ### end Alembic commands ###
