"""add is_secret to system_config and new tables

Revision ID: 4ac29fbec118
Revises: e7c676a5135a
Create Date: 2026-03-15 13:49:55.302612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac29fbec118'
down_revision: Union[str, None] = 'e7c676a5135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_chains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('call_put', sa.String(length=4), nullable=False),
    sa.Column('iv', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('oi', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_options_sym_expiry', 'options_chains', ['symbol', 'expiry'], unique=False)
    op.create_index('ix_options_sym_ts', 'options_chains', ['symbol', 'timestamp'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ask', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('mid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('spread_bps', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_sym_ts', 'quotes', ['symbol', 'timestamp'], unique=False)
    op.create_table('sentiment_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentiment_source', 'sentiment_raw', ['source'], unique=False)
    op.create_index('ix_sentiment_sym_ts', 'sentiment_raw', ['symbol', 'timestamp'], unique=False)
    op.add_column('system_config', sa.Column('is_secret', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'is_secret')
    op.drop_index('ix_sentiment_sym_ts', table_name='sentiment_raw')
    op.drop_index('ix_sentiment_source', table_name='sentiment_raw')
    op.drop_table('sentiment_raw')
    op.drop_index('ix_quotes_sym_ts', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_options_sym_ts', table_name='options_chains')
    op.drop_index('ix_options_sym_expiry', table_name='options_chains')
    op.drop_table('options_chains')
    # ### end Alembic commands ###
