"""Initial schema: 8 tables

Revision ID: e7c676a5135a
Revises: 
Create Date: 2026-03-14 21:56:08.734664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c676a5135a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('aum_bn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_daily_vol_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('spread_est_bps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('options_market', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mt5_symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etf_universe_symbol'), 'etf_universe', ['symbol'], unique=True)
    op.create_table('factor_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('calc_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('volatility_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('dispersion_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('correlation_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('breadth_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('slippage_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_scores_sym_time', 'factor_scores', ['symbol', 'calc_time'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volatility_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('num_positions', sa.Integer(), nullable=True),
    sa.Column('cash_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_date'), 'performance_metrics', ['date'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('broker_ref', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('notional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('high_watermark', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_bar_symbol_tf_ts')
    )
    op.create_index('ix_price_bars_sym_ts', 'price_bars', ['symbol', 'timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('volatility_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('breadth_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('dispersion_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('regime_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('signal_type', sa.String(length=10), nullable=True),
    sa.Column('block_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_sym_time', 'signals', ['symbol', 'signal_time'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_config_cat_key')
    )
    op.create_index(op.f('ix_system_config_category'), 'system_config', ['category'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('requested_notional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('filled_notional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mid_at_submission', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('slippage_bps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('estimated_slippage_bps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('operational_mode', sa.String(length=15), nullable=True),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_composite', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_time'), 'trades', ['trade_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_system_config_category'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index('ix_signals_sym_time', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_price_bars_sym_ts', table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_performance_metrics_date'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('ix_factor_scores_sym_time', table_name='factor_scores')
    op.drop_table('factor_scores')
    op.drop_index(op.f('ix_etf_universe_symbol'), table_name='etf_universe')
    op.drop_table('etf_universe')
    # ### end Alembic commands ###
